/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct number {
	int i;
};
typedef struct number number;

struct inputs {
	int i;
	char *j;
};
typedef struct inputs inputs;

#define RPC_PROGRAM 0x23451111
#define RPC_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define square 1
extern  int * square_1(number *, CLIENT *);
extern  int * square_1_svc(number *, struct svc_req *);
#define multiplication 2
extern  float * multiplication_1(inputs *, CLIENT *);
extern  float * multiplication_1_svc(inputs *, struct svc_req *);
#define stringify 3
extern  char ** stringify_1(number *, CLIENT *);
extern  char ** stringify_1_svc(number *, struct svc_req *);
extern int rpc_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define square 1
extern  int * square_1();
extern  int * square_1_svc();
#define multiplication 2
extern  float * multiplication_1();
extern  float * multiplication_1_svc();
#define stringify 3
extern  char ** stringify_1();
extern  char ** stringify_1_svc();
extern int rpc_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_number (XDR *, number*);
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_number ();
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
