/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"


void
rpc_program_1(char *host,int x, char y[])
{
	CLIENT *clnt;
	int  *result_1;
	number  square_1_arg;
	float  *result_2;
	inputs  multiplication_1_arg;
	char * *result_3;
	number  stringify_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_PROGRAM, RPC_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	square_1_arg.i=x;
	result_1 = square_1(&square_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("The square of (%d) is (%d).\n", square_1_arg.i, *result_1);
	}
	multiplication_1_arg.i=x;
	multiplication_1_arg.j=y;
	result_2 = multiplication_1(&multiplication_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("The product of (%d) and (%s) is (%f).\n", multiplication_1_arg.i, multiplication_1_arg.j, *result_2);
	}
	stringify_1_arg.i=x;
	result_3 = stringify_1(&stringify_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else if(*result_3=="Even"){
		printf("The number (%d) is %s.\n",stringify_1_arg.i, *result_3);
	}
	else{
		printf("The number (%d) is %s.\n",stringify_1_arg.i, *result_3);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpc_program_1 ((host), atof(argv[2]), argv[3]);
exit (0);
}
