/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

int *
square_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("The square(%d) is called.\n",argp->i);
	result = argp->i * argp->i;
	return &result;
}

float *multiplication_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;
	printf("The product of (%d) and the length (%s) is called.\n", argp->i, argp->j);
	float length=(float)strlen(argp->j);
	result = argp->i * length;
	return &result;
}

char **stringify_1_svc(number *argp, struct svc_req *rqstp)
{
	static char *result;
	
	printf("The string procedure on (%d) is called.\n",argp->i);
	
	int input = argp->i;
	
	if (input % 2 == 0){
		result = "Even";
	}
	else /*if(input % 2 == 1)*/{
		result = "Odd";
	}
	return &result;
}
